default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: local
    hooks:
    - id: black
      entry: black
      name: black
      language: system
      exclude: typings
      types_or: [cython, pyi, python]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: flake8
        entry: flake8
        name: flake8
        language: system
        exclude: '^(test/|typings/)'
        types_or: [cython, pyi, python]
